import '@rainbow-me/rainbowkit/styles.css'
import './globals.css'
import { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/providers/ThemeProvider'
// import MetamaskProvider from '@/providers'
import { Toaster } from '@/components/ui/toaster'
import { Header } from '@/components/Header'
import Footer from '@/components/Footer'
import { WalletProvider } from '@/providers/WalletProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <WalletProvider>
          {/* <MetamaskProvider> */}
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <>{children}</>
            <Footer />
            <Toaster />
          </ThemeProvider>
          {/* </MetamaskProvider> */}
        </WalletProvider>
      </body>
    </html>
  )
}
